FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json .

RUN npm ci

COPY . .

RUN npm run build

FROM node:22-alpine AS runtime

WORKDIR /app

COPY --from=build /app/dist ./dist

RUN npm install -g serve@14

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]