/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignoutRouteImport } from './routes/signout'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedConceptsMaterialIdRouteImport } from './routes/_authenticated/concepts.$materialId'
import { Route as AuthenticatedSubjectsSubjectIdRouteImport } from './routes/_authenticated/subjects.$subjectId'
import { Route as AuthenticatedSubjectsSubjectIdIndexRouteImport } from './routes/_authenticated/subjects.$subjectId.index'
import { Route as AuthenticatedSubjectsSubjectIdTopicsTopicIdRouteImport } from './routes/_authenticated/subjects.$subjectId.topics.$topicId'
import { Route as AuthenticatedSubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRouteImport } from './routes/_authenticated/subjects.$subjectId.topics.$topicId.exercises.$materialId'
import { Route as AuthenticatedSubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRouteImport } from './routes/_authenticated/subjects.$subjectId.topics.$topicId.lessons.$materialId'
import { Route as AuthenticatedSubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRouteImport } from './routes/_authenticated/subjects.$subjectId.topics.$topicId.quizzes.$materialId'
import { Route as AuthenticatedSubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRouteImport } from './routes/_authenticated/subjects.$subjectId.topics.$topicId.resources.$materialId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignoutRoute = SignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConceptsMaterialIdRoute =
  AuthenticatedConceptsMaterialIdRouteImport.update({
    id: '/concepts/$materialId',
    path: '/concepts/$materialId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubjectsSubjectIdRoute =
  AuthenticatedSubjectsSubjectIdRouteImport.update({
    id: '/subjects/$subjectId',
    path: '/subjects/$subjectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubjectsSubjectIdIndexRoute =
  AuthenticatedSubjectsSubjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSubjectsSubjectIdRoute,
  } as any)
const AuthenticatedSubjectsSubjectIdTopicsTopicIdRoute =
  AuthenticatedSubjectsSubjectIdTopicsTopicIdRouteImport.update({
    id: '/topics/$topicId',
    path: '/topics/$topicId',
    getParentRoute: () => AuthenticatedSubjectsSubjectIdRoute,
  } as any)
const AuthenticatedSubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRoute =
  AuthenticatedSubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRouteImport.update(
    {
      id: '/exercises/$materialId',
      path: '/exercises/$materialId',
      getParentRoute: () => AuthenticatedSubjectsSubjectIdTopicsTopicIdRoute,
    } as any,
  )
const AuthenticatedSubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRoute =
  AuthenticatedSubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRouteImport.update(
    {
      id: '/lessons/$materialId',
      path: '/lessons/$materialId',
      getParentRoute: () => AuthenticatedSubjectsSubjectIdTopicsTopicIdRoute,
    } as any,
  )
const AuthenticatedSubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRoute =
  AuthenticatedSubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRouteImport.update(
    {
      id: '/quizzes/$materialId',
      path: '/quizzes/$materialId',
      getParentRoute: () => AuthenticatedSubjectsSubjectIdTopicsTopicIdRoute,
    } as any,
  )
const AuthenticatedSubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRoute =
  AuthenticatedSubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRouteImport.update(
    {
      id: '/resources/$materialId',
      path: '/resources/$materialId',
      getParentRoute: () => AuthenticatedSubjectsSubjectIdTopicsTopicIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/concepts/$materialId': typeof AuthenticatedConceptsMaterialIdRoute
  '/subjects/$subjectId': typeof AuthenticatedSubjectsSubjectIdRouteWithChildren
  '/subjects/$subjectId/': typeof AuthenticatedSubjectsSubjectIdIndexRoute
  '/subjects/$subjectId/topics/$topicId': typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdRouteWithChildren
  '/subjects/$subjectId/topics/$topicId/exercises/$materialId': typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRoute
  '/subjects/$subjectId/topics/$topicId/lessons/$materialId': typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRoute
  '/subjects/$subjectId/topics/$topicId/quizzes/$materialId': typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRoute
  '/subjects/$subjectId/topics/$topicId/resources/$materialId': typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/concepts/$materialId': typeof AuthenticatedConceptsMaterialIdRoute
  '/subjects/$subjectId': typeof AuthenticatedSubjectsSubjectIdIndexRoute
  '/subjects/$subjectId/topics/$topicId': typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdRouteWithChildren
  '/subjects/$subjectId/topics/$topicId/exercises/$materialId': typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRoute
  '/subjects/$subjectId/topics/$topicId/lessons/$materialId': typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRoute
  '/subjects/$subjectId/topics/$topicId/quizzes/$materialId': typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRoute
  '/subjects/$subjectId/topics/$topicId/resources/$materialId': typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/concepts/$materialId': typeof AuthenticatedConceptsMaterialIdRoute
  '/_authenticated/subjects/$subjectId': typeof AuthenticatedSubjectsSubjectIdRouteWithChildren
  '/_authenticated/subjects/$subjectId/': typeof AuthenticatedSubjectsSubjectIdIndexRoute
  '/_authenticated/subjects/$subjectId/topics/$topicId': typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdRouteWithChildren
  '/_authenticated/subjects/$subjectId/topics/$topicId/exercises/$materialId': typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRoute
  '/_authenticated/subjects/$subjectId/topics/$topicId/lessons/$materialId': typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRoute
  '/_authenticated/subjects/$subjectId/topics/$topicId/quizzes/$materialId': typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRoute
  '/_authenticated/subjects/$subjectId/topics/$topicId/resources/$materialId': typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/dashboard'
    | '/learn'
    | '/onboarding'
    | '/profile'
    | '/concepts/$materialId'
    | '/subjects/$subjectId'
    | '/subjects/$subjectId/'
    | '/subjects/$subjectId/topics/$topicId'
    | '/subjects/$subjectId/topics/$topicId/exercises/$materialId'
    | '/subjects/$subjectId/topics/$topicId/lessons/$materialId'
    | '/subjects/$subjectId/topics/$topicId/quizzes/$materialId'
    | '/subjects/$subjectId/topics/$topicId/resources/$materialId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/dashboard'
    | '/learn'
    | '/onboarding'
    | '/profile'
    | '/concepts/$materialId'
    | '/subjects/$subjectId'
    | '/subjects/$subjectId/topics/$topicId'
    | '/subjects/$subjectId/topics/$topicId/exercises/$materialId'
    | '/subjects/$subjectId/topics/$topicId/lessons/$materialId'
    | '/subjects/$subjectId/topics/$topicId/quizzes/$materialId'
    | '/subjects/$subjectId/topics/$topicId/resources/$materialId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/learn'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/concepts/$materialId'
    | '/_authenticated/subjects/$subjectId'
    | '/_authenticated/subjects/$subjectId/'
    | '/_authenticated/subjects/$subjectId/topics/$topicId'
    | '/_authenticated/subjects/$subjectId/topics/$topicId/exercises/$materialId'
    | '/_authenticated/subjects/$subjectId/topics/$topicId/lessons/$materialId'
    | '/_authenticated/subjects/$subjectId/topics/$topicId/quizzes/$materialId'
    | '/_authenticated/subjects/$subjectId/topics/$topicId/resources/$materialId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignoutRoute: typeof SignoutRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/concepts/$materialId': {
      id: '/_authenticated/concepts/$materialId'
      path: '/concepts/$materialId'
      fullPath: '/concepts/$materialId'
      preLoaderRoute: typeof AuthenticatedConceptsMaterialIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subjects/$subjectId': {
      id: '/_authenticated/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof AuthenticatedSubjectsSubjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subjects/$subjectId/': {
      id: '/_authenticated/subjects/$subjectId/'
      path: '/'
      fullPath: '/subjects/$subjectId/'
      preLoaderRoute: typeof AuthenticatedSubjectsSubjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedSubjectsSubjectIdRoute
    }
    '/_authenticated/subjects/$subjectId/topics/$topicId': {
      id: '/_authenticated/subjects/$subjectId/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/subjects/$subjectId/topics/$topicId'
      preLoaderRoute: typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdRouteImport
      parentRoute: typeof AuthenticatedSubjectsSubjectIdRoute
    }
    '/_authenticated/subjects/$subjectId/topics/$topicId/exercises/$materialId': {
      id: '/_authenticated/subjects/$subjectId/topics/$topicId/exercises/$materialId'
      path: '/exercises/$materialId'
      fullPath: '/subjects/$subjectId/topics/$topicId/exercises/$materialId'
      preLoaderRoute: typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRouteImport
      parentRoute: typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdRoute
    }
    '/_authenticated/subjects/$subjectId/topics/$topicId/lessons/$materialId': {
      id: '/_authenticated/subjects/$subjectId/topics/$topicId/lessons/$materialId'
      path: '/lessons/$materialId'
      fullPath: '/subjects/$subjectId/topics/$topicId/lessons/$materialId'
      preLoaderRoute: typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRouteImport
      parentRoute: typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdRoute
    }
    '/_authenticated/subjects/$subjectId/topics/$topicId/quizzes/$materialId': {
      id: '/_authenticated/subjects/$subjectId/topics/$topicId/quizzes/$materialId'
      path: '/quizzes/$materialId'
      fullPath: '/subjects/$subjectId/topics/$topicId/quizzes/$materialId'
      preLoaderRoute: typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRouteImport
      parentRoute: typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdRoute
    }
    '/_authenticated/subjects/$subjectId/topics/$topicId/resources/$materialId': {
      id: '/_authenticated/subjects/$subjectId/topics/$topicId/resources/$materialId'
      path: '/resources/$materialId'
      fullPath: '/subjects/$subjectId/topics/$topicId/resources/$materialId'
      preLoaderRoute: typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRouteImport
      parentRoute: typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdRoute
    }
  }
}

interface AuthenticatedSubjectsSubjectIdTopicsTopicIdRouteChildren {
  AuthenticatedSubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRoute: typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRoute
  AuthenticatedSubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRoute: typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRoute
  AuthenticatedSubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRoute: typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRoute
  AuthenticatedSubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRoute: typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRoute
}

const AuthenticatedSubjectsSubjectIdTopicsTopicIdRouteChildren: AuthenticatedSubjectsSubjectIdTopicsTopicIdRouteChildren =
  {
    AuthenticatedSubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRoute:
      AuthenticatedSubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRoute,
    AuthenticatedSubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRoute:
      AuthenticatedSubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRoute,
    AuthenticatedSubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRoute:
      AuthenticatedSubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRoute,
    AuthenticatedSubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRoute:
      AuthenticatedSubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRoute,
  }

const AuthenticatedSubjectsSubjectIdTopicsTopicIdRouteWithChildren =
  AuthenticatedSubjectsSubjectIdTopicsTopicIdRoute._addFileChildren(
    AuthenticatedSubjectsSubjectIdTopicsTopicIdRouteChildren,
  )

interface AuthenticatedSubjectsSubjectIdRouteChildren {
  AuthenticatedSubjectsSubjectIdIndexRoute: typeof AuthenticatedSubjectsSubjectIdIndexRoute
  AuthenticatedSubjectsSubjectIdTopicsTopicIdRoute: typeof AuthenticatedSubjectsSubjectIdTopicsTopicIdRouteWithChildren
}

const AuthenticatedSubjectsSubjectIdRouteChildren: AuthenticatedSubjectsSubjectIdRouteChildren =
  {
    AuthenticatedSubjectsSubjectIdIndexRoute:
      AuthenticatedSubjectsSubjectIdIndexRoute,
    AuthenticatedSubjectsSubjectIdTopicsTopicIdRoute:
      AuthenticatedSubjectsSubjectIdTopicsTopicIdRouteWithChildren,
  }

const AuthenticatedSubjectsSubjectIdRouteWithChildren =
  AuthenticatedSubjectsSubjectIdRoute._addFileChildren(
    AuthenticatedSubjectsSubjectIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedConceptsMaterialIdRoute: typeof AuthenticatedConceptsMaterialIdRoute
  AuthenticatedSubjectsSubjectIdRoute: typeof AuthenticatedSubjectsSubjectIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedConceptsMaterialIdRoute: AuthenticatedConceptsMaterialIdRoute,
  AuthenticatedSubjectsSubjectIdRoute:
    AuthenticatedSubjectsSubjectIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SigninRoute: SigninRoute,
  SignoutRoute: SignoutRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
