/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SubjectsSubjectIdRouteImport } from './routes/subjects.$subjectId'
import { Route as SubjectsSubjectIdIndexRouteImport } from './routes/subjects.$subjectId.index'
import { Route as SubjectsSubjectIdTopicsTopicIdRouteImport } from './routes/subjects.$subjectId.topics.$topicId'
import { Route as SubjectsSubjectIdTopicsTopicIdExercisesExerciseIdRouteImport } from './routes/subjects.$subjectId.topics.$topicId.exercises.$exerciseId'
import { Route as SubjectsSubjectIdTopicsTopicIdLessonsLessonIdRouteImport } from './routes/subjects.$subjectId.topics.$topicId.lessons.$lessonId'
import { Route as SubjectsSubjectIdTopicsTopicIdQuizzesQuizIdRouteImport } from './routes/subjects.$subjectId.topics.$topicId.quizzes.$quizId'
import { Route as SubjectsSubjectIdTopicsTopicIdResourcesResourceIdRouteImport } from './routes/subjects.$subjectId.topics.$topicId.resources.$resourceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdRoute = SubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdIndexRoute = SubjectsSubjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubjectsSubjectIdRoute,
} as any)
const SubjectsSubjectIdTopicsTopicIdRoute =
  SubjectsSubjectIdTopicsTopicIdRouteImport.update({
    id: '/topics/$topicId',
    path: '/topics/$topicId',
    getParentRoute: () => SubjectsSubjectIdRoute,
  } as any)
const SubjectsSubjectIdTopicsTopicIdExercisesExerciseIdRoute =
  SubjectsSubjectIdTopicsTopicIdExercisesExerciseIdRouteImport.update({
    id: '/exercises/$exerciseId',
    path: '/exercises/$exerciseId',
    getParentRoute: () => SubjectsSubjectIdTopicsTopicIdRoute,
  } as any)
const SubjectsSubjectIdTopicsTopicIdLessonsLessonIdRoute =
  SubjectsSubjectIdTopicsTopicIdLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => SubjectsSubjectIdTopicsTopicIdRoute,
  } as any)
const SubjectsSubjectIdTopicsTopicIdQuizzesQuizIdRoute =
  SubjectsSubjectIdTopicsTopicIdQuizzesQuizIdRouteImport.update({
    id: '/quizzes/$quizId',
    path: '/quizzes/$quizId',
    getParentRoute: () => SubjectsSubjectIdTopicsTopicIdRoute,
  } as any)
const SubjectsSubjectIdTopicsTopicIdResourcesResourceIdRoute =
  SubjectsSubjectIdTopicsTopicIdResourcesResourceIdRouteImport.update({
    id: '/resources/$resourceId',
    path: '/resources/$resourceId',
    getParentRoute: () => SubjectsSubjectIdTopicsTopicIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRouteWithChildren
  '/subjects/$subjectId/': typeof SubjectsSubjectIdIndexRoute
  '/subjects/$subjectId/topics/$topicId': typeof SubjectsSubjectIdTopicsTopicIdRouteWithChildren
  '/subjects/$subjectId/topics/$topicId/exercises/$exerciseId': typeof SubjectsSubjectIdTopicsTopicIdExercisesExerciseIdRoute
  '/subjects/$subjectId/topics/$topicId/lessons/$lessonId': typeof SubjectsSubjectIdTopicsTopicIdLessonsLessonIdRoute
  '/subjects/$subjectId/topics/$topicId/quizzes/$quizId': typeof SubjectsSubjectIdTopicsTopicIdQuizzesQuizIdRoute
  '/subjects/$subjectId/topics/$topicId/resources/$resourceId': typeof SubjectsSubjectIdTopicsTopicIdResourcesResourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdIndexRoute
  '/subjects/$subjectId/topics/$topicId': typeof SubjectsSubjectIdTopicsTopicIdRouteWithChildren
  '/subjects/$subjectId/topics/$topicId/exercises/$exerciseId': typeof SubjectsSubjectIdTopicsTopicIdExercisesExerciseIdRoute
  '/subjects/$subjectId/topics/$topicId/lessons/$lessonId': typeof SubjectsSubjectIdTopicsTopicIdLessonsLessonIdRoute
  '/subjects/$subjectId/topics/$topicId/quizzes/$quizId': typeof SubjectsSubjectIdTopicsTopicIdQuizzesQuizIdRoute
  '/subjects/$subjectId/topics/$topicId/resources/$resourceId': typeof SubjectsSubjectIdTopicsTopicIdResourcesResourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRouteWithChildren
  '/subjects/$subjectId/': typeof SubjectsSubjectIdIndexRoute
  '/subjects/$subjectId/topics/$topicId': typeof SubjectsSubjectIdTopicsTopicIdRouteWithChildren
  '/subjects/$subjectId/topics/$topicId/exercises/$exerciseId': typeof SubjectsSubjectIdTopicsTopicIdExercisesExerciseIdRoute
  '/subjects/$subjectId/topics/$topicId/lessons/$lessonId': typeof SubjectsSubjectIdTopicsTopicIdLessonsLessonIdRoute
  '/subjects/$subjectId/topics/$topicId/quizzes/$quizId': typeof SubjectsSubjectIdTopicsTopicIdQuizzesQuizIdRoute
  '/subjects/$subjectId/topics/$topicId/resources/$resourceId': typeof SubjectsSubjectIdTopicsTopicIdResourcesResourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/subjects/$subjectId'
    | '/subjects/$subjectId/'
    | '/subjects/$subjectId/topics/$topicId'
    | '/subjects/$subjectId/topics/$topicId/exercises/$exerciseId'
    | '/subjects/$subjectId/topics/$topicId/lessons/$lessonId'
    | '/subjects/$subjectId/topics/$topicId/quizzes/$quizId'
    | '/subjects/$subjectId/topics/$topicId/resources/$resourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/subjects/$subjectId'
    | '/subjects/$subjectId/topics/$topicId'
    | '/subjects/$subjectId/topics/$topicId/exercises/$exerciseId'
    | '/subjects/$subjectId/topics/$topicId/lessons/$lessonId'
    | '/subjects/$subjectId/topics/$topicId/quizzes/$quizId'
    | '/subjects/$subjectId/topics/$topicId/resources/$resourceId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/signin'
    | '/subjects/$subjectId'
    | '/subjects/$subjectId/'
    | '/subjects/$subjectId/topics/$topicId'
    | '/subjects/$subjectId/topics/$topicId/exercises/$exerciseId'
    | '/subjects/$subjectId/topics/$topicId/lessons/$lessonId'
    | '/subjects/$subjectId/topics/$topicId/quizzes/$quizId'
    | '/subjects/$subjectId/topics/$topicId/resources/$resourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SigninRoute: typeof SigninRoute
  SubjectsSubjectIdRoute: typeof SubjectsSubjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId': {
      id: '/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof SubjectsSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId/': {
      id: '/subjects/$subjectId/'
      path: '/'
      fullPath: '/subjects/$subjectId/'
      preLoaderRoute: typeof SubjectsSubjectIdIndexRouteImport
      parentRoute: typeof SubjectsSubjectIdRoute
    }
    '/subjects/$subjectId/topics/$topicId': {
      id: '/subjects/$subjectId/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/subjects/$subjectId/topics/$topicId'
      preLoaderRoute: typeof SubjectsSubjectIdTopicsTopicIdRouteImport
      parentRoute: typeof SubjectsSubjectIdRoute
    }
    '/subjects/$subjectId/topics/$topicId/exercises/$exerciseId': {
      id: '/subjects/$subjectId/topics/$topicId/exercises/$exerciseId'
      path: '/exercises/$exerciseId'
      fullPath: '/subjects/$subjectId/topics/$topicId/exercises/$exerciseId'
      preLoaderRoute: typeof SubjectsSubjectIdTopicsTopicIdExercisesExerciseIdRouteImport
      parentRoute: typeof SubjectsSubjectIdTopicsTopicIdRoute
    }
    '/subjects/$subjectId/topics/$topicId/lessons/$lessonId': {
      id: '/subjects/$subjectId/topics/$topicId/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/subjects/$subjectId/topics/$topicId/lessons/$lessonId'
      preLoaderRoute: typeof SubjectsSubjectIdTopicsTopicIdLessonsLessonIdRouteImport
      parentRoute: typeof SubjectsSubjectIdTopicsTopicIdRoute
    }
    '/subjects/$subjectId/topics/$topicId/quizzes/$quizId': {
      id: '/subjects/$subjectId/topics/$topicId/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/subjects/$subjectId/topics/$topicId/quizzes/$quizId'
      preLoaderRoute: typeof SubjectsSubjectIdTopicsTopicIdQuizzesQuizIdRouteImport
      parentRoute: typeof SubjectsSubjectIdTopicsTopicIdRoute
    }
    '/subjects/$subjectId/topics/$topicId/resources/$resourceId': {
      id: '/subjects/$subjectId/topics/$topicId/resources/$resourceId'
      path: '/resources/$resourceId'
      fullPath: '/subjects/$subjectId/topics/$topicId/resources/$resourceId'
      preLoaderRoute: typeof SubjectsSubjectIdTopicsTopicIdResourcesResourceIdRouteImport
      parentRoute: typeof SubjectsSubjectIdTopicsTopicIdRoute
    }
  }
}

interface SubjectsSubjectIdTopicsTopicIdRouteChildren {
  SubjectsSubjectIdTopicsTopicIdExercisesExerciseIdRoute: typeof SubjectsSubjectIdTopicsTopicIdExercisesExerciseIdRoute
  SubjectsSubjectIdTopicsTopicIdLessonsLessonIdRoute: typeof SubjectsSubjectIdTopicsTopicIdLessonsLessonIdRoute
  SubjectsSubjectIdTopicsTopicIdQuizzesQuizIdRoute: typeof SubjectsSubjectIdTopicsTopicIdQuizzesQuizIdRoute
  SubjectsSubjectIdTopicsTopicIdResourcesResourceIdRoute: typeof SubjectsSubjectIdTopicsTopicIdResourcesResourceIdRoute
}

const SubjectsSubjectIdTopicsTopicIdRouteChildren: SubjectsSubjectIdTopicsTopicIdRouteChildren =
  {
    SubjectsSubjectIdTopicsTopicIdExercisesExerciseIdRoute:
      SubjectsSubjectIdTopicsTopicIdExercisesExerciseIdRoute,
    SubjectsSubjectIdTopicsTopicIdLessonsLessonIdRoute:
      SubjectsSubjectIdTopicsTopicIdLessonsLessonIdRoute,
    SubjectsSubjectIdTopicsTopicIdQuizzesQuizIdRoute:
      SubjectsSubjectIdTopicsTopicIdQuizzesQuizIdRoute,
    SubjectsSubjectIdTopicsTopicIdResourcesResourceIdRoute:
      SubjectsSubjectIdTopicsTopicIdResourcesResourceIdRoute,
  }

const SubjectsSubjectIdTopicsTopicIdRouteWithChildren =
  SubjectsSubjectIdTopicsTopicIdRoute._addFileChildren(
    SubjectsSubjectIdTopicsTopicIdRouteChildren,
  )

interface SubjectsSubjectIdRouteChildren {
  SubjectsSubjectIdIndexRoute: typeof SubjectsSubjectIdIndexRoute
  SubjectsSubjectIdTopicsTopicIdRoute: typeof SubjectsSubjectIdTopicsTopicIdRouteWithChildren
}

const SubjectsSubjectIdRouteChildren: SubjectsSubjectIdRouteChildren = {
  SubjectsSubjectIdIndexRoute: SubjectsSubjectIdIndexRoute,
  SubjectsSubjectIdTopicsTopicIdRoute:
    SubjectsSubjectIdTopicsTopicIdRouteWithChildren,
}

const SubjectsSubjectIdRouteWithChildren =
  SubjectsSubjectIdRoute._addFileChildren(SubjectsSubjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SigninRoute: SigninRoute,
  SubjectsSubjectIdRoute: SubjectsSubjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
