/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SubjectsSubjectIdRouteImport } from './routes/subjects.$subjectId'
import { Route as SubjectsSubjectIdIndexRouteImport } from './routes/subjects.$subjectId.index'
import { Route as SubjectsSubjectIdTopicsTopicIdRouteImport } from './routes/subjects.$subjectId.topics.$topicId'
import { Route as SubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRouteImport } from './routes/subjects.$subjectId.topics.$topicId.exercises.$materialId'
import { Route as SubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRouteImport } from './routes/subjects.$subjectId.topics.$topicId.lessons.$materialId'
import { Route as SubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRouteImport } from './routes/subjects.$subjectId.topics.$topicId.quizzes.$materialId'
import { Route as SubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRouteImport } from './routes/subjects.$subjectId.topics.$topicId.resources.$materialId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdRoute = SubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdIndexRoute = SubjectsSubjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubjectsSubjectIdRoute,
} as any)
const SubjectsSubjectIdTopicsTopicIdRoute =
  SubjectsSubjectIdTopicsTopicIdRouteImport.update({
    id: '/topics/$topicId',
    path: '/topics/$topicId',
    getParentRoute: () => SubjectsSubjectIdRoute,
  } as any)
const SubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRoute =
  SubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRouteImport.update({
    id: '/exercises/$materialId',
    path: '/exercises/$materialId',
    getParentRoute: () => SubjectsSubjectIdTopicsTopicIdRoute,
  } as any)
const SubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRoute =
  SubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRouteImport.update({
    id: '/lessons/$materialId',
    path: '/lessons/$materialId',
    getParentRoute: () => SubjectsSubjectIdTopicsTopicIdRoute,
  } as any)
const SubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRoute =
  SubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRouteImport.update({
    id: '/quizzes/$materialId',
    path: '/quizzes/$materialId',
    getParentRoute: () => SubjectsSubjectIdTopicsTopicIdRoute,
  } as any)
const SubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRoute =
  SubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRouteImport.update({
    id: '/resources/$materialId',
    path: '/resources/$materialId',
    getParentRoute: () => SubjectsSubjectIdTopicsTopicIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRouteWithChildren
  '/subjects/$subjectId/': typeof SubjectsSubjectIdIndexRoute
  '/subjects/$subjectId/topics/$topicId': typeof SubjectsSubjectIdTopicsTopicIdRouteWithChildren
  '/subjects/$subjectId/topics/$topicId/exercises/$materialId': typeof SubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRoute
  '/subjects/$subjectId/topics/$topicId/lessons/$materialId': typeof SubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRoute
  '/subjects/$subjectId/topics/$topicId/quizzes/$materialId': typeof SubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRoute
  '/subjects/$subjectId/topics/$topicId/resources/$materialId': typeof SubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdIndexRoute
  '/subjects/$subjectId/topics/$topicId': typeof SubjectsSubjectIdTopicsTopicIdRouteWithChildren
  '/subjects/$subjectId/topics/$topicId/exercises/$materialId': typeof SubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRoute
  '/subjects/$subjectId/topics/$topicId/lessons/$materialId': typeof SubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRoute
  '/subjects/$subjectId/topics/$topicId/quizzes/$materialId': typeof SubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRoute
  '/subjects/$subjectId/topics/$topicId/resources/$materialId': typeof SubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRouteWithChildren
  '/subjects/$subjectId/': typeof SubjectsSubjectIdIndexRoute
  '/subjects/$subjectId/topics/$topicId': typeof SubjectsSubjectIdTopicsTopicIdRouteWithChildren
  '/subjects/$subjectId/topics/$topicId/exercises/$materialId': typeof SubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRoute
  '/subjects/$subjectId/topics/$topicId/lessons/$materialId': typeof SubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRoute
  '/subjects/$subjectId/topics/$topicId/quizzes/$materialId': typeof SubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRoute
  '/subjects/$subjectId/topics/$topicId/resources/$materialId': typeof SubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/subjects/$subjectId'
    | '/subjects/$subjectId/'
    | '/subjects/$subjectId/topics/$topicId'
    | '/subjects/$subjectId/topics/$topicId/exercises/$materialId'
    | '/subjects/$subjectId/topics/$topicId/lessons/$materialId'
    | '/subjects/$subjectId/topics/$topicId/quizzes/$materialId'
    | '/subjects/$subjectId/topics/$topicId/resources/$materialId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/subjects/$subjectId'
    | '/subjects/$subjectId/topics/$topicId'
    | '/subjects/$subjectId/topics/$topicId/exercises/$materialId'
    | '/subjects/$subjectId/topics/$topicId/lessons/$materialId'
    | '/subjects/$subjectId/topics/$topicId/quizzes/$materialId'
    | '/subjects/$subjectId/topics/$topicId/resources/$materialId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/signin'
    | '/subjects/$subjectId'
    | '/subjects/$subjectId/'
    | '/subjects/$subjectId/topics/$topicId'
    | '/subjects/$subjectId/topics/$topicId/exercises/$materialId'
    | '/subjects/$subjectId/topics/$topicId/lessons/$materialId'
    | '/subjects/$subjectId/topics/$topicId/quizzes/$materialId'
    | '/subjects/$subjectId/topics/$topicId/resources/$materialId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SigninRoute: typeof SigninRoute
  SubjectsSubjectIdRoute: typeof SubjectsSubjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId': {
      id: '/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof SubjectsSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId/': {
      id: '/subjects/$subjectId/'
      path: '/'
      fullPath: '/subjects/$subjectId/'
      preLoaderRoute: typeof SubjectsSubjectIdIndexRouteImport
      parentRoute: typeof SubjectsSubjectIdRoute
    }
    '/subjects/$subjectId/topics/$topicId': {
      id: '/subjects/$subjectId/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/subjects/$subjectId/topics/$topicId'
      preLoaderRoute: typeof SubjectsSubjectIdTopicsTopicIdRouteImport
      parentRoute: typeof SubjectsSubjectIdRoute
    }
    '/subjects/$subjectId/topics/$topicId/exercises/$materialId': {
      id: '/subjects/$subjectId/topics/$topicId/exercises/$materialId'
      path: '/exercises/$materialId'
      fullPath: '/subjects/$subjectId/topics/$topicId/exercises/$materialId'
      preLoaderRoute: typeof SubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRouteImport
      parentRoute: typeof SubjectsSubjectIdTopicsTopicIdRoute
    }
    '/subjects/$subjectId/topics/$topicId/lessons/$materialId': {
      id: '/subjects/$subjectId/topics/$topicId/lessons/$materialId'
      path: '/lessons/$materialId'
      fullPath: '/subjects/$subjectId/topics/$topicId/lessons/$materialId'
      preLoaderRoute: typeof SubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRouteImport
      parentRoute: typeof SubjectsSubjectIdTopicsTopicIdRoute
    }
    '/subjects/$subjectId/topics/$topicId/quizzes/$materialId': {
      id: '/subjects/$subjectId/topics/$topicId/quizzes/$materialId'
      path: '/quizzes/$materialId'
      fullPath: '/subjects/$subjectId/topics/$topicId/quizzes/$materialId'
      preLoaderRoute: typeof SubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRouteImport
      parentRoute: typeof SubjectsSubjectIdTopicsTopicIdRoute
    }
    '/subjects/$subjectId/topics/$topicId/resources/$materialId': {
      id: '/subjects/$subjectId/topics/$topicId/resources/$materialId'
      path: '/resources/$materialId'
      fullPath: '/subjects/$subjectId/topics/$topicId/resources/$materialId'
      preLoaderRoute: typeof SubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRouteImport
      parentRoute: typeof SubjectsSubjectIdTopicsTopicIdRoute
    }
  }
}

interface SubjectsSubjectIdTopicsTopicIdRouteChildren {
  SubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRoute: typeof SubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRoute
  SubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRoute: typeof SubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRoute
  SubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRoute: typeof SubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRoute
  SubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRoute: typeof SubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRoute
}

const SubjectsSubjectIdTopicsTopicIdRouteChildren: SubjectsSubjectIdTopicsTopicIdRouteChildren =
  {
    SubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRoute:
      SubjectsSubjectIdTopicsTopicIdExercisesMaterialIdRoute,
    SubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRoute:
      SubjectsSubjectIdTopicsTopicIdLessonsMaterialIdRoute,
    SubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRoute:
      SubjectsSubjectIdTopicsTopicIdQuizzesMaterialIdRoute,
    SubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRoute:
      SubjectsSubjectIdTopicsTopicIdResourcesMaterialIdRoute,
  }

const SubjectsSubjectIdTopicsTopicIdRouteWithChildren =
  SubjectsSubjectIdTopicsTopicIdRoute._addFileChildren(
    SubjectsSubjectIdTopicsTopicIdRouteChildren,
  )

interface SubjectsSubjectIdRouteChildren {
  SubjectsSubjectIdIndexRoute: typeof SubjectsSubjectIdIndexRoute
  SubjectsSubjectIdTopicsTopicIdRoute: typeof SubjectsSubjectIdTopicsTopicIdRouteWithChildren
}

const SubjectsSubjectIdRouteChildren: SubjectsSubjectIdRouteChildren = {
  SubjectsSubjectIdIndexRoute: SubjectsSubjectIdIndexRoute,
  SubjectsSubjectIdTopicsTopicIdRoute:
    SubjectsSubjectIdTopicsTopicIdRouteWithChildren,
}

const SubjectsSubjectIdRouteWithChildren =
  SubjectsSubjectIdRoute._addFileChildren(SubjectsSubjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SigninRoute: SigninRoute,
  SubjectsSubjectIdRoute: SubjectsSubjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
